apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  selector:
    app: db
  type: LoadBalancer
  ports:
    - name: '3306'
      port: 3306
      targetPort: 3306
status:
  loadBalancer: {}
